# if path is empty or invalid it will use default habbo launcher path
path: ""
# country should be one of the following: us, es, br or d, if missing or invalid it will use US
country: "us"
# wether or not the client should launch in large mode or not, if missing or invalid it will launch in large mode
xl: true
# wether or not it should delete the previous version during update
delete_old_version: true